### ISSUE TITLE
logrotate configuration

### ISSUE THREAD

**Issue by cordoval** [opszero/auditkube#2]
There was some turmoil about filling the disk with the default logrotate configuration
https://github.com/kubernetes/kops/issues/2816

I think we need to make our base image more stable in this regard and configure logrotates to be 10MB instead of 100MB as it is the default. To prevent from filling 10GB of disk instead and just 1GB as max.

**Comment by cordoval** [comment]
do you thikn this should be done by an daemon set or it should be baked into the image? we need a guide on packer or a tutorial to build that but for auditkube.

**Comment by abhiyerra** [comment]
I believe the logrotate should be on the image itself.

packer.io should have a good tutorial on how to use packer.
