### ISSUE TITLE
AWS Inspector

### ISSUE THREAD

**Issue by noqcks** [opszero/auditkube#25]
I'm arduously going through PCI compliance right now with my current company. I was hoping to use AWS Inspector, but Im sad to learn that it's not supported on Debian.

Do any of your clients use AWS Inspector to be notified of vulnerable CVEs on their systems, or is there an alternative agent that's popular that I'm not aware of? I know this really isn't an issue with auditkube, but would love your input! 

From one DevOps to another ❤️.

**Comment by abhiyerra** [comment]
@noqcks We have used ThreatStack but they are not AWS only. So the answer is yes but I haven't used AWS Inspector myself.

**Comment by noqcks** [comment]
Thanks! I've seen threatstack around I'll check them out.
