### ISSUE TITLE
Kops cluster topology?

### ISSUE THREAD

**Issue by noqcks** [opszero/auditkube#28]
Hey, not a lot of information online about other people running PCI compliant workloads on Kubernetes, so apologies for the question in advance! 

I'm curious what kind of networking setup you're running on the PCI compliant kops clusters to fulfill the PCI requirement for a DMZ.

Do you satisfy inbound/outbound rules at the EC2 level w/ AWS network ACLs, or at the Kubernetes level w/ networking policies (calico)?

**Comment by abhiyerra** [comment]
@noqcks Used to do at Kubernetes level with Weave since that provided encryption now use EKS with ACLs.
