### ISSUE TITLE
public image building on all zones

### ISSUE THREAD

**Issue by cordoval** [opszero/auditkube#8]

**Comment by abhiyerra** [comment]
- [ ] Create deployment in all zones.

**Comment by cordoval** [comment]
cc @abhiyerra https://github.com/kubernetes/kube-deploy/pull/289/files

that tool wraps to build on all zones

**Comment by abhiyerra** [comment]
Fixed with AWS Marketplace Image

**Comment by cordoval** [comment]
any url?
